name: Health Check

on:
  schedule:
    - cron: "3 4 * * *" 

jobs:
  check_health:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        id: health_check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-part11-bj2u.onrender.com/

      - name: Discord Webhook Notify on success on Health Check
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: Periodic Health Check to **${{ github.repository }}**. Everything looks good!
          
      - name: Discord Webhook Notify on failure on Health Check
        if: ${{ failure() && steps.health_check.outcome == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: Periodic Health Check to **${{ github.repository }}**. Something is wrong! Production site is down!
            
      
