name: Hello World!

on:
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *" 

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
